### ISSUE TITLE
When running wasm compiled by go, I encountered an error. Please help me.

### ISSUE THREAD

**Issue by fenghaoming** [wasmerio/go-ext-wasm#132] opened 2020-04-20 04:10 UTC
When running wasm compiled by go, I encountered an error. Please help me.

The go code(test.go) to compile into wasm is as follows.
```
package main

import "fmt"

func main() {
	rs := Dododo(54, 21)
	fmt.Println(fmt.Sprintf("rs: %d", rs))
}

func Dododo(x int, y int) int {
	return x - y
}
```

Then compile to wasm.
```
$ GOOS=js GOARCH=wasm go build -o test.wasm test.go
```

The code to run wasm is as follows.
```
package main

import (
	"fmt"
	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
)

func main() {
	testTest()
}

func testTest() {
	bytes, err := wasm.ReadBytes("test.wasm")
	if err != nil {
		fmt.Printf(fmt.Sprintf("Error wasm.ReadBytes, err: %s", err))
		return
	}

	instance, err := wasm.NewInstance(bytes)
	if err != nil {
		fmt.Printf(fmt.Sprintf("Error wasm.NewInstance, err: %s", err))
		return
	}
	defer instance.Close()

	Dododo := instance.Exports["Dododo"]

	result, err := Dododo(86, 37)
	if err != nil {
		fmt.Printf(fmt.Sprintf("Error Dododo, err: %s", err))
		return
	}

	fmt.Println(result)
}
```

Then the error message is as follows.
```
Error wasm.NewInstance, err: Failed to instantiate the module:
    19 link errors: (1 of 19) Import not found, namespace: go, name: debug (2 of 19) Import not found, namespace: go, name: runtime.wasmExit (3 of 19) Import not found, namespace: go, name: runtime.wasmWrite (4 of 19) Import not found, namespace: go, name: runtime.nanotime (5 of 19) Import not found, namespace: go, name: runtime.walltime (6 of 19) Import not found, namespace: go, name: runtime.scheduleTimeoutEvent (7 of 19) Import not found, namespace: go, name: runtime.clearTimeoutEvent (8 of 19) Import not found, namespace: go, name: runtime.getRandomData (9 of 19) Import not found, namespace: go, name: syscall/js.stringVal (10 of 19) Import not found, namespace: go, name: syscall/js.valueGet (11 of 19) Import not found, namespace: go, name: syscall/js.valueSet (12 of 19) Import not found, namespace: go, name: syscall/js.valueIndex (13 of 19) Import not found, namespace: go, name: syscall/js.valueSetIndex (14 of 19) Import not found, namespace: go, name: syscall/js.valueCall (15 of 19) Import not found, namespace: go, name: syscall/js.valueNew (16 of 19) Import not found, namespace: go, name: syscall/js.valueLength (17 of 19) Import not found, namespace: go, name: syscall/js.valuePrepareString (18 of 19) Import not found, namespace: go, name: syscall/js.valueLoadString (19 of 19) Import not found, namespace: go, name: syscall/js.copyBytesToJS
```

**Comment by fenghaoming** [comment] 2020-04-20 04:13
> When running wasm compiled by go, I encountered an error. Please help me.
> 
> The go code(test.go) to compile into wasm is as follows.
> 
> ```
> package main
> 
> import "fmt"
> 
> func main() {
> 	rs := Dododo(54, 21)
> 	fmt.Println(fmt.Sprintf("rs: %d", rs))
> }
> 
> func Dododo(x int, y int) int {
> 	return x - y
> }
> ```
> 
> Then compile to wasm.
> 
> ```
> $ GOOS=js GOARCH=wasm go build -o test.wasm test.go
> ```
> 
> The code to run wasm is as follows.
> 
> ```
> package main
> 
> import (
> 	"fmt"
> 	wasm "github.com/wasmerio/go-ext-wasm/wasmer"
> )
> 
> func main() {
> 	testTest()
> }
> 
> func testTest() {
> 	bytes, err := wasm.ReadBytes("test.wasm")
> 	if err != nil {
> 		fmt.Printf(fmt.Sprintf("Error wasm.ReadBytes, err: %s", err))
> 		return
> 	}
> 
> 	instance, err := wasm.NewInstance(bytes)
> 	if err != nil {
> 		fmt.Printf(fmt.Sprintf("Error wasm.NewInstance, err: %s", err))
> 		return
> 	}
> 	defer instance.Close()
> 
> 	Dododo := instance.Exports["Dododo"]
> 
> 	result, err := Dododo(86, 37)
> 	if err != nil {
> 		fmt.Printf(fmt.Sprintf("Error Dododo, err: %s", err))
> 		return
> 	}
> 
> 	fmt.Println(result)
> }
> ```
> 
> Then the error message is as follows.
> 
> ```
> Error wasm.NewInstance, err: Failed to instantiate the module:
>     19 link errors: (1 of 19) Import not found, namespace: go, name: debug (2 of 19) Import not found, namespace: go, name: runtime.wasmExit (3 of 19) Import not found, namespace: go, name: runtime.wasmWrite (4 of 19) Import not found, namespace: go, name: runtime.nanotime (5 of 19) Import not found, namespace: go, name: runtime.walltime (6 of 19) Import not found, namespace: go, name: runtime.scheduleTimeoutEvent (7 of 19) Import not found, namespace: go, name: runtime.clearTimeoutEvent (8 of 19) Import not found, namespace: go, name: runtime.getRandomData (9 of 19) Import not found, namespace: go, name: syscall/js.stringVal (10 of 19) Import not found, namespace: go, name: syscall/js.valueGet (11 of 19) Import not found, namespace: go, name: syscall/js.valueSet (12 of 19) Import not found, namespace: go, name: syscall/js.valueIndex (13 of 19) Import not found, namespace: go, name: syscall/js.valueSetIndex (14 of 19) Import not found, namespace: go, name: syscall/js.valueCall (15 of 19) Import not found, namespace: go, name: syscall/js.valueNew (16 of 19) Import not found, namespace: go, name: syscall/js.valueLength (17 of 19) Import not found, namespace: go, name: syscall/js.valuePrepareString (18 of 19) Import not found, namespace: go, name: syscall/js.valueLoadString (19 of 19) Import not found, namespace: go, name: syscall/js.copyBytesToJS
> ```

Could you give me an example of go code to compile into wasm and run on this project? Thanks!

**Comment by fenghaoming** [comment] 2020-04-20 04:15
Could you please give me an example of go code to compile into wasm and run on this project? Thanks!

**Comment by Hywan** [comment] 2020-05-05 15:09
Check #95 to learn more. Go compiler generates Wasm module tailored for JS only for the moment. Closing this issue, as it is duplicate of others, but #95 is the central discussion.

**Closed by Hywan** 2020-05-05 15:09 UTC
Labels: ❓ question
