### ISSUE TITLE
Handling panics in wasm code?

### ISSUE THREAD

**Issue by rusenask** [wasmerio/go-ext-wasm#98] opened 2019-12-12 11:51 UTC
### Summary

Hello, let's suppose I have an exported function in Rust that I call and it does:

```
panic!("time to panic");
```

I would probably expect that the function will return an error, but I get this:

```
SIGABRT: abort
PC=0x7f23653747bb m=0 sigcode=18446744073709551610

goroutine 405 [running]:
runtime: unknown pc 0x7f23653747bb
stack: frame={sp:0xc0000097d0, fp:0x0} stack=[0xc000016000,0xc00001a000)

runtime: unknown pc 0x7f23653747bb
stack: frame={sp:0xc0000097d0, fp:0x0} stack=[0xc000016000,0xc00001a000)

created by github.com/rusenask/reactor/vendor/google.golang.org/grpc.(*Server).serveStreams.func1
	/usr/local/go/src/github.com/rusenask/reactor/vendor/google.golang.org/grpc/server.go:715 +0xa1
....
....
```

and it just stops. Ideally I wouldn't want my application to crash. Should I try catching SIGABRT and ignore it?

**Comment by Hywan** [comment] 2019-12-12 14:15
Thanks for opening the issue!

I believe it's a duplicate of #58. Closing the issue.

**Closed by Hywan** 2019-12-12 14:15 UTC
Labels: ❓ question
